version: '3'

services:
  app:
    container_name: api-characters
    image: api-characters
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - .:/app
